import { Col, Row } from 'antd'
import { captureRejectionSymbol } from 'events'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1>Hello???</h1>
      </Container>
    </div>
  )
}

const Container = ({children} : any) => {
  return <Row justify='center'>
    <Col span={4}>    
      {children}
    </Col>
  </Row>
}

export default Home
