override: true
schema: ${NEXT_PUBLIC_ENDPOINT}/graphql
documents: './src/api/**/*.graphql'
generates:
  ./src/api/generated/api.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        endpoint: ${NEXT_PUBLIC_ENDPOINT}/graphql
        fetchParams:
          headers:
            Content-Type: application/json