override: true
schema:
  - ${NEXT_PUBLIC_ENDPOINT}:
      headers:
        Authorization: ${API_ACCESS_TOKEN}
documents: './src/api/**/*.graphql'
config:
  namingConvention: ./src/api/fixNames.js
generates:
  ./src/api/generated/api.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unknown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node